### ISSUE TITLE
Captcha protection

### ISSUE THREAD

**Issue by breeky** [benoitdemaegdt/TGVmax#34]
Hi,

First, your project is amazing ! I wanted to try it on my own so I designed a little website to try your method (Solution 3 option 2 in your ReadMe.md). But I'm currently facing a big problem : if there are too many call to the SNCF api, the api returns this html page :

 ` <html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Validation</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body style="font-family:verdana;">      
Nos systèmes ont détecté un trafic exceptionnel sur votre réseau informatique.<br>
Pour continuer à utiliser notre site, cochez la case ci-dessous. <br>Nous nous assurons ainsi que vous êtes un être humain, et pas un robot.<br><br>
    <form method="POST">
      <div class="g-recaptcha" data-sitekey="6LfSSfkSAAAAADF4KnlarXLOSrQiSCQNqZpvtlcQ"></div>
      <input type="hidden" name="formname" value="vsccaptcha">
      <br/>
      <input type="submit" value="Envoyer">
    </form>
</body>
</html> `

...a google reCaptcha. Do you have any idea to avoid this problem ? 

Thank you very much for this.

**Comment by benoitdemaegdt** [comment]
Hi,

So far I never faced this issue, but it sounds really bad ...
What was the request frequency when you got this captcha ? More than 1 req / second ?
And how long did you run your code before getting this ?

**Comment by breeky** [comment]
A script checked every 5 minutes if the travel was available in Tgvmax. This worked for a couple hours but I think the captcha appeared when I ran the script a lot to debug it. Before this debug, everything worked fine. So maybe if I check the captcha once, it will work again but I don't know how to check it with a script...

**Comment by benoitdemaegdt** [comment]
@breeky thanks a lot for this EDIT, this is gonna be useful.
Following what you said, I'll add a delay in my code 😄
