### ISSUE TITLE
SNCF api

### ISSUE THREAD

**Issue by Lazare-C** [benoitdemaegdt/TGVmax#490]
I don't know if the problem comes from me but after a fresh install I have a error:

`21-07-2020 20:40:00 - processing 2 travelAlerts

21-07-2020 20:40:00 - using sncf connector

SNCF API ERROR : 500 VersionCompatibilityException

21-07-2020 20:40:00 - using sncf connector

SNCF API ERROR : 500 VersionCompatibilityException`

**Comment by benoitdemaegdt** [comment]
fixed : https://github.com/benoitdemaegdt/TGVmax/commit/479d28d488204dbb79c0929f423af7a970c3f036

SNCF changes its API version every 3-4 weeks.

**Comment by Lazare-C** [comment]
You looked to use the trainline API. Because it seems simple enough to me

**Comment by benoitdemaegdt** [comment]
you cannot use trainline api anymore for a multi users app.
see : https://github.com/tducret/trainline-python/issues/11

should be ok if you're building something for your own use however 😉

**Comment by Lazare-C** [comment]
Why not, when I have time to do an external api with my account...
But why not use https://simulateur.tgvmax.fr/VSC/ knowing that for the moment the API is quite simple to use.

**Comment by benoitdemaegdt** [comment]
1. I'm not sure this simulator existed 1 year ago when I created the app
2. As this simulator is web based, you'll probably face captchas that will make it very hard to fetch data

However I wasn't aware of this simulator, and It probably worth a try 👍
